# SwiftLint 配置文件
# Smarteller 项目代码质量检查配置

# 禁用的规则
disabled_rules:
  - trailing_whitespace  # 允许行尾空格（在某些情况下有用）
  - todo                 # 允许 TODO 注释
  - line_length         # 使用自定义行长度限制

# 启用的可选规则
opt_in_rules:
  - empty_count                    # 使用 isEmpty 而不是 count == 0
  - explicit_init                  # 显式初始化
  - first_where                    # 使用 first(where:) 而不是 filter().first
  - contains_over_first_not_nil    # 使用 contains 而不是 first != nil
  - empty_string                   # 使用 isEmpty 而不是 == ""
  - fatal_error_message            # fatal_error 需要包含消息
  - force_unwrapping              # 避免强制解包
  - implicitly_unwrapped_optional  # 避免隐式解包可选值
  - overridden_super_call         # 重写方法应调用 super
  - redundant_nil_coalescing      # 避免冗余的 nil 合并
  - switch_case_alignment         # switch case 对齐
  - unneeded_parentheses_in_closure_argument  # 闭包参数不需要括号
  - vertical_whitespace_closing_braces        # 闭合括号前的垂直空白
  - vertical_whitespace_opening_braces        # 开放括号后的垂直空白

# 包含的文件路径
included:
  - Smarteller/Smarteller
  - SmartellerTests
  - SmartellerUITests

# 排除的文件路径
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - Smarteller/Smarteller.xcodeproj
  - Smarteller/Smarteller/Resources

# 自定义规则配置
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 400
  error: 1000
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# 自定义规则
custom_rules:
  # 强制使用 self 在闭包中
  explicit_self_in_closures:
    name: "Explicit self in closures"
    regex: '\{[^}]*(?:^|\s)(?!self\.)([a-zA-Z_][a-zA-Z0-9_]*(?:\.[a-zA-Z_][a-zA-Z0-9_]*)*)\s*='
    message: "Use explicit 'self.' in closures"
    severity: warning
  
  # 避免使用 print 语句
  no_print:
    name: "No print statements"
    regex: '\bprint\s*\('
    message: "Use proper logging instead of print statements"
    severity: warning
  
  # 强制使用 guard 语句进行早期返回
  prefer_guard:
    name: "Prefer guard statements"
    regex: 'if\s+.*\s*\{\s*return'
    message: "Consider using guard statement for early returns"
    severity: warning

# 报告格式
reporter: "xcode"

# 严格模式（将警告视为错误）
strict: false

# 并行执行
parallel_execution: true

# 缓存路径
cache_path: ".swiftlint_cache"